name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]  # Chạy khi có thay đổi trên nhánh main
  workflow_dispatch:  # Cho phép chạy thủ công từ Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # ✅ Dùng phiên bản mới nhất
        with:
          name: github-pages
          path: ./public  # Thư mục chứa site đã build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

