name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Verify Hugo configuration
        run: |
          ls -la
          if [ ! -f config.toml ] && [ ! -f config.yaml ] && [ ! -f config.json ]; then
            echo "Error: No Hugo configuration file found!" && exit 1
          fi

      - name: Build site
        run: hugo --minify
        env:
          HUGO_ENV: production

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
